const express = require('express');
const sqlite3 = require('sqlite3').verbose();
const cors = require('cors');
const bodyParser = require('body-parser');

const app = express();
const PORT = 3000;

// Middleware
app.use(cors());
app.use(bodyParser.json());

// Database Setup
const db = new sqlite3.Database('./sudoku.db', (err) => {
  if (err) {
    console.error('Error opening database', err.message);
  } else {
    console.log('Connected to the SQLite database.');
    
    // Create Tables
    db.run(`CREATE TABLE IF NOT EXISTS puzzles (
      id TEXT PRIMARY KEY,
      initialGrid TEXT,
      solvedGrid TEXT,
      difficulty TEXT,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS scores (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      puzzleId TEXT,
      playerName TEXT,
      timeSeconds INTEGER,
      mistakes INTEGER,
      timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
    )`);
  }
});

// --- API ROUTES ---

// 1. Save a new Puzzle (Generated by the app)
app.post('/api/puzzle', (req, res) => {
  const { id, initialGrid, solvedGrid, difficulty } = req.body;
  
  if (!id || !initialGrid || !solvedGrid) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  const query = `INSERT OR IGNORE INTO puzzles (id, initialGrid, solvedGrid, difficulty) VALUES (?, ?, ?, ?)`;
  db.run(query, [id, JSON.stringify(initialGrid), JSON.stringify(solvedGrid), difficulty], function(err) {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json({ message: 'Puzzle saved', id });
  });
});

// 2. Get a Puzzle by ID
app.get('/api/puzzle/:id', (req, res) => {
  const { id } = req.params;
  db.get(`SELECT * FROM puzzles WHERE id = ?`, [id], (err, row) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ error: 'Puzzle not found' });
    }
    res.json({
      id: row.id,
      initialGrid: JSON.parse(row.initialGrid),
      solvedGrid: JSON.parse(row.solvedGrid),
      difficulty: row.difficulty
    });
  });
});

// 3. Submit a Score
app.post('/api/score', (req, res) => {
  const { puzzleId, playerName, timeSeconds, mistakes } = req.body;
  
  const query = `INSERT INTO scores (puzzleId, playerName, timeSeconds, mistakes) VALUES (?, ?, ?, ?)`;
  db.run(query, [puzzleId, playerName, timeSeconds, mistakes], function(err) {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json({ message: 'Score saved', id: this.lastID });
  });
});

// 4. Get Leaderboard (Global or by Puzzle)
app.get('/api/leaderboard', (req, res) => {
  const { puzzleId } = req.query;
  
  let query = `SELECT * FROM scores ORDER BY mistakes ASC, timeSeconds ASC LIMIT 50`;
  let params = [];

  if (puzzleId) {
    query = `SELECT * FROM scores WHERE puzzleId = ? ORDER BY mistakes ASC, timeSeconds ASC LIMIT 50`;
    params = [puzzleId];
  }

  db.all(query, params, (err, rows) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json(rows);
  });
});

// Start Server
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server running on http://0.0.0.0:${PORT}`);
});
